import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => { errors.push(error.message); console.log('Page error:', error.message); });
page.on('console', message => { if (message.type() === 'error') console.log('Console error:', message.text()); });
await page.goto('http://127.0.0.1:5173');
await page.waitForFunction(() => !!window.kingdom);
await page.waitForTimeout(900);
await page.evaluate(() => { window.kingdom.game.paused = true; window.kingdom.updateHUD(); });
await page.locator('#paused-indicator').evaluate(e => e.style.visibility = 'hidden');
await page.screenshot({ path: 'test-results/initial.png' });
await page.locator('#paused-indicator').evaluate(e => e.style.visibility = '');
console.log('Ready:', await page.evaluate(() => ({ selected: document.getElementById('selection-name').textContent, entities: window.kingdom.game.entities.length, size: [window.kingdom.renderer.width, window.kingdom.renderer.height] })));
assert.equal(await page.locator('#selection-name').textContent(), 'Town Center');
await page.getByRole('button', { name: 'Villager', exact: true }).click();
assert.equal(await page.evaluate(() => window.kingdom.game.own(0, 'building').find(b => b.type === 'towncenter').queue.length), 1);
await page.locator('[data-queue="0"]').click();
assert.equal(await page.evaluate(() => window.kingdom.game.own(0, 'building').find(b => b.type === 'towncenter').queue.length), 0);
await page.getByRole('button', { name: 'How to play', exact: true }).click();
assert.equal(await page.locator('[role="dialog"]').count(), 1);
await page.screenshot({ path: 'test-results/help.png' });
await page.getByRole('button', { name: 'RETURN TO YOUR KINGDOM' }).click();
await page.locator('#menu-button').click();
await page.getByRole('button', { name: 'SAVE GAME', exact: true }).click();
assert.match(await page.locator('#save-message').textContent(), /Campaign saved/);
const savedFood = await page.evaluate(() => window.kingdom.game.players[0].resources.food);
await page.evaluate(() => window.kingdom.game.players[0].resources.food += 123);
await page.getByRole('button', { name: 'LOAD GAME', exact: true }).click();
assert.equal(await page.evaluate(() => window.kingdom.game.players[0].resources.food), savedFood);
await page.evaluate(() => { window.kingdom.game.paused = true; window.kingdom.updateHUD(); });
await page.locator('#army-button').click();
assert.equal(await page.locator('#selection-name').textContent(), 'Scout Cavalry');
await page.getByRole('button', { name: 'Explore', exact: true }).click();
assert.equal(await page.evaluate(() => window.kingdom.selection[0].autoExplore), true);
await page.keyboard.press('h');
assert.equal(await page.locator('#selection-name').textContent(), 'Town Center');

// Select an actual Villager on the map, gather, place and complete a Barracks.
const villagerPoint = await page.evaluate(() => { const u = window.kingdom.game.own(0, 'unit').filter(u => u.type === 'villager')[4]; return window.kingdom.renderer.screen(u.x, u.y, 10); });
const mapBounds = await page.locator('#world').boundingBox();
await page.mouse.click(villagerPoint.x + mapBounds.x, villagerPoint.y + mapBounds.y);
assert.equal(await page.locator('#selection-name').textContent(), 'Villager');
await page.getByRole('button', { name: 'Gather Wood', exact: true }).click();
assert.equal(await page.evaluate(() => window.kingdom.selection[0].order.resource), 'wood');
await page.getByRole('button', { name: 'Build', exact: true }).click();
await page.screenshot({ path: 'test-results/build-menu.png' });
await page.getByRole('button', { name: 'Barracks', exact: true }).click();
const buildingPoint = await page.evaluate(() => window.kingdom.renderer.screen(20.3, 25.3));
await page.mouse.click(mapBounds.x + buildingPoint.x, mapBounds.y + buildingPoint.y);
assert.equal(await page.locator('#selection-name').textContent(), 'Barracks');
await page.evaluate(() => { const g = window.kingdom.game; g.paused = false; for (let i = 0; i < 400; i++) g.update(.1); g.paused = true; window.kingdom.updateHUD(); });
assert.equal(await page.evaluate(() => window.kingdom.selection[0].progress), 1);
await page.getByRole('button', { name: 'Militia', exact: true }).click();
await page.evaluate(() => { const g = window.kingdom.game; g.paused = false; for (let i = 0; i < 160; i++) g.update(.1); g.paused = true; window.kingdom.updateHUD(); });
assert.equal(await page.evaluate(() => window.kingdom.game.own(0, 'unit').filter(u => u.type === 'militia').length), 1);
await page.keyboard.press('h');
await page.getByRole('button', { name: 'Advance to Feudal Age', exact: true }).click();
assert.equal(await page.evaluate(() => window.kingdom.selection[0].queue[0]?.kind), 'age');
await page.evaluate(() => { const g = window.kingdom.game; g.paused = false; for (let i = 0; i < 500; i++) g.update(.1); g.paused = true; window.kingdom.updateHUD(); });
assert.equal(await page.locator('#age-name').textContent(), 'Feudal Age');

// Inspect the laptop layout, camera, zoom, and pause controls.
await page.setViewportSize({ width: 1280, height: 800 });
await page.waitForTimeout(250);
await page.locator('#paused-indicator').evaluate(e => e.style.visibility = 'hidden');
await page.screenshot({ path: 'test-results/feudal-laptop.png' });
await page.locator('#paused-indicator').evaluate(e => e.style.visibility = '');
const oldZoom = await page.evaluate(() => window.kingdom.renderer.zoom);
await page.locator('#zoom-in').click();
assert.ok(await page.evaluate(() => window.kingdom.renderer.zoom) > oldZoom);
await page.locator('#minimap').click({ position: { x: 150, y: 45 } });
await page.keyboard.press('h');
await page.locator('#pause-button').click();
assert.equal(await page.evaluate(() => window.kingdom.game.paused), false);
await page.locator('#pause-button').click();
assert.equal(await page.evaluate(() => window.kingdom.game.paused), true);

// Run and render a full match with paid construction, economy, and army production.
await page.setViewportSize({ width: 1440, height: 900 });
await page.evaluate(async () => {
  const { Game } = await import('/src/game.js');
  const { playCampaign } = await import('/tests/campaign-strategy.js');
  window.kingdom.reset(new Game('standard'));
  playCampaign(window.kingdom.game, 480);
  window.kingdom.game.paused = true;
  document.getElementById('announcements').innerHTML = '';
  window.kingdom.home(); window.kingdom.updateHUD();
});
await page.locator('#paused-indicator').evaluate(e => e.style.visibility = 'hidden');
await page.waitForTimeout(200);
await page.screenshot({ path: 'test-results/castle-settlement.png' });
await page.locator('#paused-indicator').evaluate(e => e.style.visibility = '');
const result = await page.evaluate(async () => { const { playCampaign } = await import('/tests/campaign-strategy.js'); window.kingdom.game.paused = false; return playCampaign(window.kingdom.game); });
assert.equal(result.result, 'victory');
assert.equal(await page.locator('#result-title').textContent(), 'An empire is born.');
await page.screenshot({ path: 'test-results/victory.png' });
await page.getByRole('button', { name: 'FOUND ANOTHER KINGDOM' }).click();
await page.locator('[data-difficulty="peaceful"]').click();
await page.getByRole('button', { name: 'BEGIN YOUR CAMPAIGN' }).click();
assert.equal(await page.evaluate(() => window.kingdom.game.difficulty), 'peaceful');
assert.equal(await page.locator('#age-name').textContent(), 'Dark Age');

// Touch selection and command mode work without a mouse or keyboard.
const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
mobile.on('pageerror', error => errors.push(error.message));
await mobile.goto('http://127.0.0.1:5173');
await mobile.waitForFunction(() => !!window.kingdom);
await mobile.evaluate(() => { window.kingdom.game.paused = true; window.kingdom.updateHUD(); });
await mobile.locator('#paused-indicator').evaluate(e => e.style.visibility = 'hidden');
await mobile.screenshot({ path: 'test-results/mobile.png' });
assert.ok(await mobile.evaluate(() => document.querySelector('.topbar').scrollWidth <= innerWidth + 1), 'Mobile header should fit');
const mobileMap = await mobile.locator('#world').boundingBox();
const touchVillager = await mobile.evaluate(() => { const u = window.kingdom.game.own(0, 'unit').filter(u => u.type === 'villager')[1]; return window.kingdom.renderer.screen(u.x, u.y, 10); });
await mobile.touchscreen.tap(mobileMap.x + touchVillager.x, mobileMap.y + touchVillager.y);
assert.equal(await mobile.locator('#selection-name').textContent(), 'Villager');
await mobile.locator('#touch-command').tap();
const touchTarget = await mobile.evaluate(() => window.kingdom.renderer.screen(18.5, 29.5));
await mobile.touchscreen.tap(mobileMap.x + touchTarget.x, mobileMap.y + touchTarget.y);
assert.equal(await mobile.evaluate(() => window.kingdom.selection[0].order.type), 'move');
await mobile.close();
console.log('Full browser campaign:', { result: result.result, time: Math.round(result.time), age: result.player.age, trained: result.player.stats.trained });
console.log('Browser errors:', errors);
assert.deepEqual(errors, []);
await browser.close();
console.log('Browser smoke checks passed.');
