const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#world'),ctx=canvas.getContext('2d'),mini=$('#minimap'),mc=mini.getContext('2d');
const N=60,TW=64,TH=32,icons={food:'🌾',wood:'🪵',gold:'◆',stone:'⬟',pop:'♟'};
const AGES=['Dark Age','Feudal Age','Castle Age','Imperial Age'];
const DATA={
 villager:{name:'Villager',icon:'♟',cost:{food:50},time:12,hp:55,atk:4,range:1.2,speed:2.25,desc:'Gathers resources and constructs your settlement.'},
 militia:{name:'Man-at-arms',icon:'⚔',cost:{food:60,gold:20},time:14,hp:110,atk:13,range:1.3,speed:2.25,desc:'Reliable infantry. Strong in numbers.'},
 archer:{name:'Archer',icon:'➶',cost:{wood:40,gold:35},time:16,hp:65,atk:10,range:6,speed:2.15,age:1,desc:'Ranged soldiers. Keep them behind your infantry.'},
 knight:{name:'Knight',icon:'♞',cost:{food:80,gold:60},time:22,hp:230,atk:24,range:1.4,speed:3.3,age:2,desc:'Heavy cavalry. Fast, durable and powerful.'},
 ram:{name:'Battering ram',icon:'♜',cost:{wood:140,gold:75},time:28,hp:320,atk:12,range:1.8,speed:1.35,age:2,desc:'Deals 95 damage to buildings. Protect it from enemy soldiers.'},
 trebuchet:{name:'Trebuchet',icon:'♜',cost:{wood:200,gold:150},time:35,hp:180,atk:28,range:13,speed:1,age:3,desc:'Long-range siege. Deals 150 damage to buildings from beyond their defenses.'},
 town:{name:'Town Center',icon:'♜',size:3,hp:2600,atk:18,range:8,pop:10,train:['villager'],desc:'The heart of your kingdom. Trains villagers and defends the settlement.'},
 house:{name:'House',icon:'⌂',cost:{wood:65},size:2,hp:450,time:15,pop:5,desc:'Provides room for 5 more people.'},
 farm:{name:'Farm',icon:'▤',cost:{wood:60},size:2,hp:250,time:10,desc:'An enduring source of food. Assign a villager to tend it.'},
 barracks:{name:'Barracks',icon:'⚔',cost:{wood:160},size:3,hp:1100,time:28,train:['militia'],desc:'Trains men-at-arms for your army.'},
 range:{name:'Archery Range',icon:'➶',cost:{wood:180},size:3,hp:1000,time:28,age:1,train:['archer'],desc:'Trains archers to strike from a distance.'},
 stable:{name:'Stable',icon:'♞',cost:{wood:200},size:3,hp:1200,time:32,age:2,train:['knight'],desc:'Trains armored knights for powerful cavalry charges.'},
 siege:{name:'Siege Workshop',icon:'⚙',cost:{wood:220},size:3,hp:1000,time:32,age:2,train:['ram','trebuchet'],desc:'Constructs rams to break enemy strongholds.'},
 tower:{name:'Watchtower',icon:'♜',cost:{wood:70,stone:110},size:2,hp:1000,time:27,atk:18,range:9,age:1,desc:'Automatically fires at approaching enemies.'},
 castle:{name:'Castle',icon:'♛',cost:{stone:500,wood:150},size:4,hp:3500,time:65,atk:40,range:11,age:2,pop:10,desc:'A mighty fortress with devastating defensive fire.'},
 blacksmith:{name:'Blacksmith',icon:'⚒',cost:{wood:150},size:2,hp:800,time:24,age:1,desc:'Research armor and weapons for your entire army.'}
};
let W,H,dpr,cam={x:0,y:0,zoom:.95},S,terrain=[],nodes=[],entities=[],effects=[],selected=[],placement=null,commandMode=null,nextId=1,keys={},mouse={x:0,y:0},drag=null,pan=null,last=0,uiTick=0,saveTick=0,visionTick=0,aiTick=0,terrainCanvas;
let difficulty='standard',started=false,paused=true,ended=false,controlGroups={},audioCtx=null,soundOn=true;
let rngSeed=17347;function rand(){rngSeed=(rngSeed*1664525+1013904223)>>>0;return rngSeed/4294967296}const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),idx=(x,y)=>Math.floor(y)*N+Math.floor(x);
function project(x,y){return{x:(x-y)*TW/2,y:(x+y)*TH/2}}function screen(x,y){const p=project(x,y);return{x:(p.x-cam.x)*cam.zoom+W/2,y:(p.y-cam.y)*cam.zoom+H*.48}}function unproject(x,y){let a=(x-W/2)/cam.zoom+cam.x,b=(y-H*.48)/cam.zoom+cam.y;return{x:a/TW+b/TH,y:b/TH-a/TW}}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function entity(type,owner,x,y,complete=true){const d=DATA[type];let e={id:nextId++,type,owner,x,y,hp:d.hp,maxHp:d.hp,building:!!d.size,progress:complete?1:0,queue:[],task:null,path:[],cooldown:0,anim:rand()*6,rally:null};entities.push(e);return e}
function alive(){return entities.filter(e=>e.hp>0)}function byId(id){return entities.find(e=>e.id===id&&e.hp>0)||nodes.find(e=>e.id===id&&e.amount>0)}
function generate(){rngSeed=17347;nextId=1;terrain=[];nodes=[];entities=[];effects=[];selected=[];controlGroups={};S={time:0,age:[0,0],resources:[{food:340,wood:360,gold:160,stone:180},{food:500,wood:600,gold:250,stone:300}],explored:new Array(N*N).fill(0),visible:new Array(N*N).fill(0),upgrades:[{attack:0,armor:0},{attack:0,armor:0}],research:null,kills:0,gathered:0,raid:0,nextRaid: difficulty==='relaxed'?420:difficulty==='hard'?150:270,stats:{trained:0,built:0},difficulty};
 for(let y=0;y<N;y++)for(let x=0;x<N;x++){let water=((x-41)**2/110+(y-44)**2/25<1)||((x-8)**2/24+(y-12)**2/45<1);let road=Math.abs(y-(34-(x-18)*.65))<1.2&&x>12&&x<49;terrain.push({x,y,type:water?'water':road?'road':'grass',r:rand()})}
 for(let y=2;y<N-2;y++)for(let x=2;x<N-2;x++){let nearHome=Math.hypot(x-18,y-34)<7,nearEnemy=Math.hypot(x-43,y-17)<7;let density=(Math.sin(x*.31+y*.23)+Math.sin(y*.5-x*.21))*.07+.13;if(!nearHome&&!nearEnemy&&terrain[idx(x,y)].type==='grass'&&rand()<density)nodes.push({id:nextId++,kind:'tree',resource:'wood',x:x+.15+rand()*.7,y:y+.15+rand()*.7,amount:180,r:rand()})}
 const patch=(x,y,kind,res,count)=>{for(let i=0;i<count;i++){let xx=x+(i%3)*.85+rand()*.3,yy=y+Math.floor(i/3)*.9+rand()*.3;nodes=nodes.filter(n=>n.kind!=='tree'||dist(n,{x:xx,y:yy})>1);nodes.push({id:nextId++,kind,resource:res,x:xx,y:yy,amount:kind==='berry'?230:700,r:rand()})}};
 patch(13,30,'berry','food',7);patch(24,34,'gold','gold',6);patch(16,40,'stone','stone',5);patch(40,21,'berry','food',7);patch(48,18,'gold','gold',6);patch(38,13,'stone','stone',5);patch(29,22,'gold','gold',8);patch(34,31,'stone','stone',7);patch(11,43,'berry','food',5);
 for(let i=0;i<13;i++)nodes.push({id:nextId++,kind:'tree',resource:'wood',x:10+rand()*3,y:34+rand()*5,amount:200,r:rand()});
 for(const [owner,x,y] of [[0,18,34],[1,43,17]]){entity('town',owner,x,y);entity('house',owner,x-4,y+1);entity('house',owner,x+2,y+4);entity('farm',owner,x-1,y-4);for(let i=0;i<7;i++){let v=entity('villager',owner,x-2+i*.6,y+2.6);if(i<3)assignGather(v,nearestNode(v,'food'));else if(i<6)assignGather(v,nearestNode(v,'wood'));else assignGather(v,nearestNode(v,'gold'))}entity('militia',owner,x+3,y-2);if(owner===1){entity('barracks',1,x+4,y-4);entity('militia',1,x+2,y-3);entity('militia',1,x+3,y-3)}}
 for(let i=0;i<11;i++)nodes.push({id:nextId++,kind:'deer',resource:null,x:25+rand()*5,y:40+rand()*4,amount:1,r:rand()});
 const p=project(19,33);cam.x=p.x;cam.y=p.y;cam.zoom=Math.min(1.05,W/1350);selected=[entities.find(e=>e.owner===0&&e.type==='town').id];updateVision();makeTerrain();updateUI(true)}
function blocked(x,y,ignore=null){if(x<1||y<1||x>=N-1||y>=N-1)return true;if(terrain[idx(x,y)]?.type==='water')return true;return entities.some(e=>e.hp>0&&e.building&&e.type!=='farm'&&e.id!==ignore&&Math.abs(x+.5-e.x)<DATA[e.type].size/2+.1&&Math.abs(y+.5-e.y)<DATA[e.type].size/2+.1)}
function findPath(a,b){let sx=Math.floor(a.x),sy=Math.floor(a.y),gx=clamp(Math.floor(b.x),1,N-2),gy=clamp(Math.floor(b.y),1,N-2);if(blocked(gx,gy)){let best=null;for(let r=1;r<5&&!best;r++){let opts=[];for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++)if(!blocked(gx+dx,gy+dy))opts.push({x:gx+dx,y:gy+dy});opts.sort((c,d)=>Math.hypot(c.x-a.x,c.y-a.y)-Math.hypot(d.x-a.x,d.y-a.y));best=opts[0]}if(best){gx=best.x;gy=best.y}else return[]}
 let open=[{x:sx,y:sy,g:0,f:0}],seen=new Map(),parent=new Map(),closed=new Set(),target=gy*N+gx;seen.set(sy*N+sx,0);let end=null,iterations=0;
 while(open.length&&iterations++<1800){let best=0;for(let i=1;i<open.length;i++)if(open[i].f<open[best].f)best=i;let c=open.splice(best,1)[0],ci=c.y*N+c.x;if(ci===target){end=ci;break}if(closed.has(ci))continue;closed.add(ci);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;let x=c.x+dx,y=c.y+dy,ni=y*N+x;if(blocked(x,y)||closed.has(ni)||(dx&&dy&&(blocked(c.x+dx,c.y)||blocked(c.x,c.y+dy))))continue;let ng=c.g+(dx&&dy?1.414:1);if(ng<(seen.get(ni)??Infinity)){seen.set(ni,ng);parent.set(ni,ci);open.push({x,y,g:ng,f:ng+Math.hypot(gx-x,gy-y)})}}}
 if(end===null)return[];let path=[];while(end!==sy*N+sx){path.unshift({x:end%N+.5,y:Math.floor(end/N)+.5});end=parent.get(end);if(end===undefined)break}return path}
function moveTo(e,p){e.path=findPath(e,p);e.dest={x:p.x,y:p.y};e.repath=0}function nearestNode(e,res){let available=nodes.filter(n=>n.amount>0&&n.resource===res);if(res==='food')available.push(...entities.filter(n=>n.hp>0&&n.type==='farm'&&n.owner===e.owner&&n.progress>=1));available.sort((a,b)=>dist(e,a)-dist(e,b));return available[0]}
function assignGather(e,n){if(!n)return;e.task={kind:'gather',target:n.id,resource:n.resource||'food'};moveTo(e,n)}
function count(owner,type){return entities.filter(e=>e.hp>0&&e.owner===owner&&(!type||e.type===type)).length}function population(owner){return entities.filter(e=>e.hp>0&&e.owner===owner&&!e.building).length}function cap(owner){return Math.min(150,entities.filter(e=>e.hp>0&&e.owner===owner&&e.progress>=1).reduce((s,e)=>s+(DATA[e.type].pop||0),0))}
function afford(cost,owner=0){return Object.entries(cost||{}).every(([k,v])=>S.resources[owner][k]>=v)}function pay(cost,owner=0){for(let[k,v]of Object.entries(cost||{}))S.resources[owner][k]-=v}function costText(cost){return Object.entries(cost||{}).map(([k,v])=>`${icons[k]} ${v}`).join('   ')}
function notify(text,warn=false){const el=document.createElement('div');el.className='toast'+(warn?' warn':'');el.textContent=text;$('#notifications').append(el);setTimeout(()=>el.remove(),6000);if($('#notifications').children.length>4)$('#notifications').firstChild.remove()}
function tone(freq=350,dur=.07,type='sine',vol=.035){if(!soundOn||!audioCtx)return;try{let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch{}}
function train(b,type){if(!b||b.progress<1)return;let d=DATA[type],o=b.owner;if((d.age||0)>S.age[o])return;if(!afford(d.cost,o)){if(!o)notify('Not enough resources. '+costText(d.cost),true);return}let queued=entities.filter(e=>e.owner===o).reduce((a,e)=>a+e.queue.filter(q=>q.type).length,0);if(population(o)+queued>=cap(o)){if(!o)notify('More houses are needed to grow your population.',true);return}if(b.queue.length>=6){if(!o)notify('Training queue is full.',true);return}pay(d.cost,o);b.queue.push({type,left:d.time,total:d.time});tone(480);updateUI(true)}
function validSite(type,x,y){let s=DATA[type].size;for(let yy=Math.floor(y-s/2);yy<y+s/2;yy++)for(let xx=Math.floor(x-s/2);xx<x+s/2;xx++)if(xx<1||yy<1||xx>=N-1||yy>=N-1||terrain[idx(xx,yy)]?.type==='water')return false;if(entities.some(e=>e.hp>0&&e.building&&Math.abs(x-e.x)<(s+DATA[e.type].size)/2+.25&&Math.abs(y-e.y)<(s+DATA[e.type].size)/2+.25))return false;return !nodes.some(n=>n.kind!=='deer'&&n.amount>0&&Math.abs(n.x-x)<s/2&&Math.abs(n.y-y)<s/2)}
function place(type,x,y,owner=0,builders=[]){const d=DATA[type];if(!afford(d.cost,owner)||!validSite(type,x,y))return null;pay(d.cost,owner);let b=entity(type,owner,x,y,false);b.hp=d.hp*.15;builders.forEach(v=>{v.task={kind:'build',target:b.id};moveTo(v,b)});if(!owner){S.stats.built++;notify(`${d.name} foundation laid.`);tone(220,.1)}return b}
function advanceAge(owner=0){let age=S.age[owner],cost=age===0?{food:450,gold:150}:age===1?{food:750,gold:400}:{food:1000,gold:700};if(age>=3||owner===0&&S.research)return;if(!afford(cost,owner)){if(!owner)notify('Age advancement requires '+costText(cost),true);return}pay(cost,owner);if(owner===0){S.research={kind:'age',left:age===0?40:55,total:age===0?40:55};notify('Your scholars are preparing a new age.')}else S.age[1]++;updateUI(true)}
function upgrade(kind){let level=S.upgrades[0][kind];let cost={food:120+level*90,gold:100+level*80};if(level>=S.age[0]||S.research)return;if(!afford(cost)){notify('Upgrade requires '+costText(cost),true);return}pay(cost);S.research={kind,left:25,total:25};notify('Research begun.');updateUI(true)}
function commandAt(p,target){let units=selected.map(byId).filter(e=>e&&e.owner===0&&!e.building);if(!units.length){for(let e of selected.map(byId).filter(e=>e?.building&&e.owner===0)){e.rally=p;notify('Rally point set.')}return}for(let i=0;i<units.length;i++){let e=units[i];if(target&&target.owner===1){e.task={kind:'attack',target:target.id};moveTo(e,target)}else if(e.type==='villager'&&target?.building&&target.owner===0&&target.progress<1){e.task={kind:'build',target:target.id};moveTo(e,target)}else if(e.type==='villager'&&target&&(target.resource||target.type==='farm'))assignGather(e,target);else if(e.type==='villager'&&target?.building&&target.owner===0&&target.hp<target.maxHp){e.task={kind:'repair',target:target.id};moveTo(e,target)}else {const off={x:p.x+(i%4-Math.min(3,units.length-1)/2)*.65,y:p.y+Math.floor(i/4)*.65};e.task={kind:commandMode==='attackMove'?'attackMove':'move',x:off.x,y:off.y};moveTo(e,off)}}effects.push({kind:'ring',x:p.x,y:p.y,life:.7,max:.7,color:target?.owner===1?'#e58662':'#e9d694'});tone(target?.owner===1?170:520,.07);commandMode=null;updateUI(true)}
function damage(target,amount,attacker){if(target.hp<=0)return;const armor=S.upgrades[target.owner]?.armor||0;target.hp-=Math.max(1,amount-(target.building?0:armor*2));target.hit=.18;if(target.owner===0&&S.time-(S.lastWarn||-100)>25){S.lastWarn=S.time;notify('Your kingdom is under attack!',true)}if(!target.building&&(!target.task||target.task.kind==='gather')&&target.type!=='villager'){target.task={kind:'attack',target:attacker.id};moveTo(target,attacker)}if(target.hp<=0){if(attacker.owner===0&&target.owner===1)S.kills++;effects.push({kind:'death',x:target.x,y:target.y,life:2,max:2,building:target.building});if(target.building){for(let q of target.queue)if(q.type)for(let[k,v]of Object.entries(DATA[q.type].cost))S.resources[target.owner][k]+=v*.5;target.queue=[];if(target.owner===0)notify(`Your ${DATA[target.type].name} has fallen.`,true)}tone(90,.15,'triangle',.03);selected=selected.filter(id=>id!==target.id);checkEnd()}}
function attack(e,t,dt){const d=DATA[e.type],reach=(d.range||1.2)+(t.building?DATA[t.type].size*.48:0);if((t.building?Math.hypot(Math.max(0,Math.abs(e.x-t.x)-DATA[t.type].size/2),Math.max(0,Math.abs(e.y-t.y)-DATA[t.type].size/2)):dist(e,t))>(t.building?(d.range||1.2)+.4:reach)){if(!e.building){e.repath=(e.repath||0)-dt;if(!e.path.length||e.repath<=0){moveTo(e,t);e.repath=1.3}}return false}e.path=[];if(e.cooldown<=0){let power=d.atk+S.age[e.owner]*2+S.upgrades[e.owner].attack*3;if(e.type==='ram'&&t.building)power=95;if(e.type==='trebuchet'&&t.building)power=150;if(t.building&&e.type==='archer')power*=.4;e.cooldown=e.type==='trebuchet'?5:e.type==='ram'?2.2:e.building?1.5:1.05;e.attackAnim=.3;if(d.range>2){effects.push({kind:e.type==='trebuchet'?'stone':'arrow',x:e.x,y:e.y,tx:t.x,ty:t.y,life:.28,max:.28,fromHeight:e.building?65:18});}damage(t,power,e)}return true}
function update(dt){if(paused||!started)return;S.time+=dt;for(let e of entities){if(e.hp<=0)continue;e.cooldown-=dt;e.hit=Math.max(0,(e.hit||0)-dt);e.attackAnim=Math.max(0,(e.attackAnim||0)-dt);e.anim+=dt;if(e.building){if(e.progress<1)continue;if(e.queue.length){let q=e.queue[0];q.left-=dt;if(q.left<=0){if(population(e.owner)>=cap(e.owner)){q.left=0;continue}let pos=null;for(let r=2;r<6&&!pos;r++)for(let j=0;j<12&&!pos;j++){let a=j/12*Math.PI*2,p={x:e.x+Math.cos(a)*r,y:e.y+Math.sin(a)*r};if(!blocked(Math.floor(p.x),Math.floor(p.y)))pos=p}if(pos){let u=entity(q.type,e.owner,pos.x,pos.y);if(e.owner===0){S.stats.trained++;if(q.type==='villager')assignGather(u,nearestNode(u,'food'));if(e.rally){u.task={kind:'move',...e.rally};moveTo(u,e.rally)}}else if(q.type==='villager'){const res=['food','wood','gold'][count(1,'villager')%3];assignGather(u,nearestNode(u,res))}e.queue.shift();tone(660,.12)}}}if(DATA[e.type].atk){let foes=entities.filter(f=>f.hp>0&&f.owner!==e.owner&&!f.building&&dist(e,f)<DATA[e.type].range);foes.sort((a,b)=>dist(e,a)-dist(e,b));if(foes[0])attack(e,foes[0],dt)}continue}
 let task=e.task;if(task?.kind==='attack'){let t=byId(task.target);if(!t||t.hp<=0){e.task=null;e.path=[]}else attack(e,t,dt)}
 else if(task?.kind==='gather'||task?.kind==='build'||task?.kind==='repair'){let t=byId(task.target);if(!t||t.amount<=0){if(task.kind==='gather'){let n=nearestNode(e,task.resource);if(n)assignGather(e,n);else e.task=null}else e.task=null}else{let reach=t.building?DATA[t.type].size*.5+1.65:.95;if(dist(e,t)<reach){e.path=[];if(task.kind==='gather'){let amount=dt*(task.resource==='food'?1.8:1.6)*(1+S.age[e.owner]*.15);S.resources[e.owner][task.resource]+=amount;if(!e.owner)S.gathered+=amount;if(t.amount)t.amount-=amount;e.work=true}else if(task.kind==='build'){let amount=dt/DATA[t.type].time;t.progress=Math.min(1,t.progress+amount);t.hp=Math.min(t.maxHp,t.hp+amount*t.maxHp*.85);e.work=true;if(t.progress>=1){if(!e.owner)notify(`${DATA[t.type].name} completed.`);if(t.type==='farm')assignGather(e,t);else e.task=null;updateUI(true)}}else{if(S.resources[e.owner].wood>dt*1.2){t.hp=Math.min(t.maxHp,t.hp+dt*25);S.resources[e.owner].wood-=dt*1.2;e.work=true}if(t.hp>=t.maxHp)e.task=null}}else if(!e.path.length)moveTo(e,t)}}
 if(e.type!=='villager'&&(!e.task||e.task.kind==='attackMove')){e.scan=(e.scan||0)-dt;if(e.scan<=0){e.scan=.5;const foes=entities.filter(f=>f.hp>0&&f.owner!==e.owner&&dist(e,f)<(e.type==='archer'?7:5.5));foes.sort((a,b)=>dist(e,a)-dist(e,b));if(foes[0]){e.resume=e.task;e.task={kind:'attack',target:foes[0].id};moveTo(e,foes[0])}}}
 if(e.path.length){let p=e.path[0],dd=dist(e,p),speed=DATA[e.type].speed*dt;if(dd<=speed){e.x=p.x;e.y=p.y;e.path.shift()}else{e.x+=(p.x-e.x)/dd*speed;e.y+=(p.y-e.y)/dd*speed}e.facing=p.x>e.x?1:-1;e.work=false}else if(e.task?.kind==='move')e.task=null;
 if(!e.task&&e.resume){e.task=e.resume;e.resume=null;moveTo(e,e.task)}
 }
 for(let e of entities){if(e.hp<=0||e.building)continue;for(let other of entities){if(other.id<=e.id||other.hp<=0||other.building)continue;let dx=e.x-other.x,dy=e.y-other.y,dd=Math.hypot(dx,dy);if(dd<.42&&dd>.001){let push=(.42-dd)*Math.min(.4,dt*4)/dd;let nx=e.x+dx*push,ny=e.y+dy*push;if(!blocked(Math.floor(nx),Math.floor(ny))){e.x=nx;e.y=ny}nx=other.x-dx*push;ny=other.y-dy*push;if(!blocked(Math.floor(nx),Math.floor(ny))){other.x=nx;other.y=ny}}}}
 if(S.research){S.research.left-=dt;if(S.research.left<=0){if(S.research.kind==='age'){S.age[0]++;notify(`Welcome to the ${AGES[S.age[0]]}. New possibilities await.`);tone(780,.5,'sine',.06)}else{S.upgrades[0][S.research.kind]++;notify('Research complete. Your army grows stronger.')}S.research=null;updateUI(true)}}
 for(let f of effects)f.life-=dt;effects=effects.filter(f=>f.life>0);visionTick-=dt;if(visionTick<=0){updateVision();visionTick=.45}aiTick-=dt;if(aiTick<=0){updateAI();aiTick=2.5}saveTick+=dt;if(saveTick>25){saveTick=0;saveGame(false)}checkEnd();}
function updateVision(){S.visible.fill(0);for(let e of entities){if(e.owner!==0||e.hp<=0)continue;const r=e.building?(e.type==='town'?13:9):8;for(let y=Math.max(0,Math.floor(e.y-r));y<Math.min(N,e.y+r);y++)for(let x=Math.max(0,Math.floor(e.x-r));x<Math.min(N,e.x+r);x++)if((x-e.x)**2+(y-e.y)**2<r*r){S.visible[idx(x,y)]=1;S.explored[idx(x,y)]=1}}}
function aiBuild(type){let base=entities.find(e=>e.owner===1&&e.type==='town'&&e.hp>0);if(!base)return;for(let r=5;r<14;r+=2)for(let a=0;a<Math.PI*2;a+=.55){let x=Math.round(base.x+Math.cos(a)*r),y=Math.round(base.y+Math.sin(a)*r);if(validSite(type,x,y)){let builder=entities.filter(e=>e.owner===1&&e.type==='villager'&&e.hp>0&&e.task?.kind!=='build').sort((a,b)=>dist(a,{x,y})-dist(b,{x,y}))[0];if(builder)return place(type,x,y,1,[builder]);return}}}
function updateAI(){if(ended)return;const o=1,age=S.age[1],t=S.time,bank=S.resources[1];let base=entities.find(e=>e.owner===1&&e.type==='town'&&e.hp>0);if(!base)return;let factor=difficulty==='hard'?1.4:difficulty==='relaxed'?.65:1;for(let k of ['food','wood','gold'])bank[k]+=2*factor;for(let e of entities.filter(e=>e.owner===1&&e.hp>0&&e.type==='villager'&&!e.task))assignGather(e,nearestNode(e,bank.food<350?'food':bank.wood<280?'wood':'gold'));
 if(population(1)+4>=cap(1)&&afford(DATA.house.cost,1)&&!entities.some(e=>e.owner===1&&e.type==='house'&&e.progress<1))aiBuild('house');if(count(1,'villager')<18&&base.queue.length<1)train(base,'villager');
 if(age===0&&t>160/factor&&afford({food:450,gold:150},1))advanceAge(1);if(age===1&&t>450/factor&&afford({food:750,gold:400},1))advanceAge(1);if(age===2&&t>750/factor&&afford({food:1000,gold:700},1))advanceAge(1);
 for(let type of ['barracks',...(age>=1?['range']:[]),...(age>=2?['stable','siege']:[])])if(!count(1,type)&&afford(DATA[type].cost,1))aiBuild(type);
 const army=entities.filter(e=>e.hp>0&&e.owner===1&&!e.building&&e.type!=='villager');for(let b of entities.filter(e=>e.hp>0&&e.owner===1&&e.building&&DATA[e.type].train&&e.type!=='town'))if(b.progress>=1&&b.queue.length<1&&army.length<(difficulty==='relaxed'?18:32))train(b,b.type==='siege'&&age>=3&&army.filter(u=>u.type==='trebuchet').length<3?'trebuchet':DATA[b.type].train[0]);
 const invaders=entities.filter(e=>e.hp>0&&e.owner===0&&!e.building&&dist(e,base)<13);if(invaders.length){for(let u of army.filter(u=>dist(u,base)<16)){let target=invaders.reduce((a,b)=>dist(u,a)<dist(u,b)?a:b);u.task={kind:'attack',target:target.id};if(!u.path.length)moveTo(u,target)}}
 if(t>S.nextRaid&&army.length>=5){S.raid++;S.nextRaid=t+(difficulty==='hard'?95:difficulty==='relaxed'?200:145);const target=entities.find(e=>e.owner===0&&e.type==='town'&&e.hp>0)||entities.find(e=>e.owner===0&&e.hp>0);if(target){const force=army.slice(0,Math.min(army.length-2,(difficulty==='hard'?5:difficulty==='relaxed'?1:3)+S.raid*2));for(let u of force){u.task={kind:'attackMove',x:target.x,y:target.y};moveTo(u,target)}notify('Scouts report a Raven warband marching on your settlement.',true)}}}
function checkEnd(){if(ended||!started)return;let p=entities.some(e=>e.hp>0&&e.owner===0&&e.type==='town'),enemy=entities.some(e=>e.hp>0&&e.owner===1&&['town','barracks','range','stable','siege','castle'].includes(e.type));if(!p)endGame(false);else if(!enemy)endGame(true)}
function endGame(win){ended=true;paused=true;$('#endEyebrow').textContent=win?'THE VALLEY IS YOURS':'THE CROWN HAS FALLEN';$('#endTitle').textContent=win?'An empire rises.':'A kingdom remembered.';$('#endText').textContent=`${win?'House Raven has been defeated. Your people will sing of this day.':'Your Town Center has fallen to House Raven. The valley awaits a new ruler.'} ${Math.floor(S.time/60)} minutes · ${S.kills} enemies defeated · ${S.stats.built} buildings raised.`;$('#endModal').classList.remove('hidden');localStorage.removeItem('crown-save')}
function poly(c,points,fill,stroke){c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=.7;c.stroke()}}
function ellipse(c,x,y,rx,ry,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill()}
function makeTerrain(){terrainCanvas=document.createElement('canvas');terrainCanvas.width=N*TW+128;terrainCanvas.height=N*TH+128;const c=terrainCanvas.getContext('2d');c.translate(N*TW/2+64,50);for(let t of terrain){let p=project(t.x,t.y),r=t.r;let water=t.type==='water',road=t.type==='road';let col=water?`hsl(${177+r*12},22%,${26+r*8}%)`:road?`hsl(48,22%,${38+r*6}%)`:`hsl(${80+r*4},${26+r*4}%,${35+r*2+Math.sin(t.x*.23+t.y*.3)*1.3}%)`;poly(c,[[p.x,p.y],[p.x+32,p.y+16],[p.x,p.y+32],[p.x-32,p.y+16]],col);if(!water){for(let i=0;i<8;i++){let a=((r*17+i*.137)%1),b=((r*33+i*.293)%1),q=project(t.x+a,t.y+b);c.fillStyle=i%3?'#d3d08d18':'#1a412626';c.fillRect(q.x,q.y,1.5+i%3,1)}if(r>.83&&!road){let q=project(t.x+.5,t.y+.5);c.strokeStyle='#35552c66';c.lineWidth=.7;for(let i=0;i<3;i++){c.beginPath();c.moveTo(q.x+i*3,q.y);c.lineTo(q.x+i*3-2,q.y-3-i);c.stroke()}}}else{c.strokeStyle='#c0d0ae25';c.beginPath();c.moveTo(p.x-9,p.y+15);c.lineTo(p.x+8,p.y+15);c.stroke()}}
 // Well-worn ground around both settlements.
 for(let [x,y]of [[18,34],[43,17]]){let p=project(x,y),g=c.createRadialGradient(p.x,p.y,8,p.x,p.y,155);g.addColorStop(0,'#a89a6c55');g.addColorStop(1,'#a89a6c00');c.save();c.translate(p.x,p.y);c.scale(1,.5);c.fillStyle=g; c.restore();ellipse(c,p.x,p.y,105,45,'#a5935c12')}
}
function box(x,y,w,h,z,top,left,right,base=0){const a=project(x-w/2,y-h/2),b=project(x+w/2,y-h/2),c=project(x+w/2,y+h/2),d=project(x-w/2,y+h/2);poly(ctx,[[d.x,d.y-base],[c.x,c.y-base],[c.x,c.y-z],[d.x,d.y-z]],left,'#302e2733');poly(ctx,[[b.x,b.y-base],[c.x,c.y-base],[c.x,c.y-z],[b.x,b.y-z]],right,'#302e2733');poly(ctx,[[a.x,a.y-z],[b.x,b.y-z],[c.x,c.y-z],[d.x,d.y-z]],top);return{a,b,c,d}}
function roof(x,y,w,h,z,rise,color){const a=project(x-w/2,y-h/2),b=project(x+w/2,y-h/2),c=project(x+w/2,y+h/2),d=project(x-w/2,y+h/2),m1=project(x,y-h/2),m2=project(x,y+h/2);poly(ctx,[[d.x-4,d.y-z],[c.x+4,c.y-z],[m2.x,m2.y-z-rise]],color[0]);poly(ctx,[[a.x-4,a.y-z],[d.x-4,d.y-z],[m2.x,m2.y-z-rise],[m1.x,m1.y-z-rise]],color[0],'#201f2233');poly(ctx,[[b.x+4,b.y-z],[c.x+4,c.y-z],[m2.x,m2.y-z-rise],[m1.x,m1.y-z-rise]],color[1],'#201f2255');ctx.strokeStyle='#e7b48428';ctx.lineWidth=1;for(let i=1;i<7;i++){let f=i/7;ctx.beginPath();ctx.moveTo(b.x+4+(m1.x-b.x-4)*f,b.y-z+(m1.y-rise-b.y)*f);ctx.lineTo(c.x+4+(m2.x-c.x-4)*f,c.y-z+(m2.y-rise-c.y)*f);ctx.stroke()}}
function flag(x,y,height,owner,t=0){let p=project(x,y);ctx.strokeStyle='#5a5040';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x,p.y-height);ctx.stroke();let wave=Math.sin(S.time*3+t)*3;poly(ctx,[[p.x,p.y-height],[p.x+19,p.y-height+3+wave],[p.x+16,p.y-height+16+wave],[p.x,p.y-height+13]],owner?'#a6493d':'#468eac','#1b373344');ctx.fillStyle='#e9d9a5';ctx.fillRect(p.x+4,p.y-height+5,3,6);ellipse(ctx,p.x,p.y-height-2,2,2,'#d5ba76')}
function drawBuilding(e,ghost=false){let d=DATA[e.type],p=project(e.x,e.y),s=d.size,color=e.owner?['#934f40','#633e36']:['#527d89','#36576a'];ctx.save();if(ghost)ctx.globalAlpha=.55;ellipse(ctx,p.x+11,p.y+10,s*27,s*12,'#14271945');
 if(e.type==='farm'){let a=project(e.x-1,e.y-1),b=project(e.x+1,e.y-1),c=project(e.x+1,e.y+1),dd=project(e.x-1,e.y+1);poly(ctx,[[a.x,a.y],[b.x,b.y],[c.x,c.y],[dd.x,dd.y]],'#7e683e','#574c31');for(let i=0;i<8;i++){let yy=e.y-.9+i*.25,q=project(e.x-.88,yy),r=project(e.x+.88,yy);ctx.strokeStyle=i%2?'#c1ab57':'#596d35';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(q.x,q.y-2);ctx.lineTo(r.x,r.y-2);ctx.stroke();for(let j=0;j<8;j++){let z=project(e.x-.8+j*.23,yy);ctx.strokeStyle='#d1bc60';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(z.x,z.y);ctx.lineTo(z.x-1,z.y-6);ctx.stroke()}}for(let q of [a,b,c,dd]){ctx.fillStyle='#9c8052';ctx.fillRect(q.x-1,q.y-8,2,9)}ctx.restore();return}
 if(e.progress<1&&!ghost){box(e.x,e.y,s-.15,s-.15,5,'#8a8164','#6c6851','#595d49');let z=5+e.progress*40;const corners=[project(e.x-s/2+.2,e.y-s/2+.2),project(e.x+s/2-.2,e.y-s/2+.2),project(e.x+s/2-.2,e.y+s/2-.2),project(e.x-s/2+.2,e.y+s/2-.2)];ctx.strokeStyle='#a79366';ctx.lineWidth=3;corners.forEach(q=>{ctx.beginPath();ctx.moveTo(q.x,q.y);ctx.lineTo(q.x,q.y-z-15);ctx.stroke()});for(let i=0;i<4;i++){let a=corners[i],b=corners[(i+1)%4];ctx.beginPath();ctx.moveTo(a.x,a.y-z);ctx.lineTo(b.x,b.y-z);ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y-z);ctx.stroke()}ellipse(ctx,p.x,p.y+7,17,6,'#74694e');ctx.fillStyle='#b4a583';ctx.fillRect(p.x-12,p.y-5,19,11);ctx.restore();return}
 if(e.type==='town'){box(e.x,e.y,2.8,2.8,8,'#a7a081','#827d65','#736f59');box(e.x,e.y-.35,2.35,1.65,44,'#c9c0a0','#c1b694','#9e987d');roof(e.x,e.y-.35,2.65,1.95,44,36,['#9f6947','#795039']);box(e.x-.1,e.y-.55,.78,.8,82,'#d4c5a1','#c5b88f','#9b9478',44);roof(e.x-.1,e.y-.55,1,1,82,23,color);flag(e.x-.1,e.y-.55,121,e.owner);box(e.x,e.y+1,1.5,.7,27,'#b7ae8a','#c0b08b','#9e9574');roof(e.x,e.y+1,1.8,.95,28,15,color);let q=project(e.x+.1,e.y+1.38);ctx.fillStyle='#4b4938';ctx.fillRect(q.x-8,q.y-23,15,21);ctx.strokeStyle='#8f7c55';ctx.strokeRect(q.x-8,q.y-23,15,21);for(let i=-1;i<=1;i+=2){let q=project(e.x+i*.72,e.y+.5);ctx.fillStyle='#4b5547';ctx.fillRect(q.x-4,q.y-33,8,10)}for(let i=0;i<3;i++){let q=project(e.x+.8+i*.3,e.y+1.4);ellipse(ctx,q.x,q.y-2,5,3,'#8c7248');ctx.fillStyle='#aa8b54';ctx.fillRect(q.x-4,q.y-10,8,8)}}
 else if(e.type==='tower'||e.type==='castle'){let castle=e.type==='castle';box(e.x,e.y,s*.85,s*.85,castle?60:68,'#9e9c8b','#a4a38e','#7e8577');if(castle){box(e.x,e.y,1.6,1.6,100,'#b6b19a','#b0ac91','#898f7e');roof(e.x,e.y,1.85,1.85,100,32,color);for(let dx of [-1.3,1.3])for(let dy of [-1.3,1.3]){box(e.x+dx,e.y+dy,.85,.85,78,'#b8b49d','#a7a58f','#838b7c');for(let xx of [-.3,.3])for(let yy of [-.3,.3])box(e.x+dx+xx,e.y+dy+yy,.23,.23,85,'#c5bea1','#aaa990','#939880')}flag(e.x,e.y,147,e.owner)}else{box(e.x,e.y,1.05,1.05,76,'#aeb29b','#a3a88f','#808b79');for(let xx of [-.4,.4])for(let yy of [-.4,.4])box(e.x+xx,e.y+yy,.3,.3,86,'#c5c2a1','#b8b396','#8d9681');flag(e.x,e.y,109,e.owner)}let q=project(e.x,e.y+s*.43);ctx.fillStyle='#3b453b';ctx.fillRect(q.x-8,q.y-25,16,25);ctx.fillStyle='#464d40';ctx.fillRect(p.x-3,p.y-57,5,13)}
 else{let big=s===3;let z=big?34:28;box(e.x,e.y,s-.3,s-.3,5,'#999477','#7a7960','#636b54');box(e.x,e.y,s-.6,s-.6,z,'#b7ad8e','#bbae8b','#999578');let roofColor=e.type==='house'?['#9b754b','#70583d']:color;roof(e.x,e.y,s-.35,s-.35,z,big?31:24,roofColor);let q=project(e.x+.1,e.y+(s-.6)/2);ctx.fillStyle='#48493a';ctx.fillRect(q.x-6,q.y-19,12,19);ctx.strokeStyle='#897651';ctx.lineWidth=1;ctx.strokeRect(q.x-6,q.y-19,12,19);ctx.strokeStyle='#665d44';ctx.lineWidth=3;const fr=project(e.x-(s-.6)/2,e.y+(s-.6)/2);ctx.beginPath();ctx.moveTo(fr.x,fr.y-z);ctx.lineTo(fr.x,fr.y);ctx.lineTo(q.x+20,q.y+10);ctx.stroke();let win=project(e.x+(s-.6)/2,e.y-.4);ctx.fillStyle='#3c534d';ctx.fillRect(win.x-4,win.y-21,8,10);if(e.type==='house'||e.type==='blacksmith'){box(e.x-.45,e.y-.3,.3,.35,z+24,'#b0a28b','#9c917b','#726e60',z+4);if(!ghost)for(let i=0;i<3;i++){let pp=project(e.x-.45,e.y-.3),phase=(S.time*.45+i*.32)%1;ellipse(ctx,pp.x+phase*12,pp.y-z-26-phase*30,4+phase*8,3+phase*6,`rgba(210,211,184,${.18*(1-phase)})`)}}if(big)flag(e.x+.7,e.y-.4,z+66,e.owner);if(e.type==='barracks'){let a=project(e.x-1,e.y+1.3);ctx.strokeStyle='#b9b8a2';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x-8,a.y);ctx.lineTo(a.x+8,a.y-26);ctx.moveTo(a.x+8,a.y);ctx.lineTo(a.x-8,a.y-26);ctx.stroke();ellipse(ctx,a.x,a.y-9,7,8,e.owner?'#9b5345':'#5e93a1')}if(e.type==='range'){let a=project(e.x+1.2,e.y+1);ellipse(ctx,a.x,a.y-13,10,14,'#bba982');ellipse(ctx,a.x,a.y-13,7,10,'#8c493c');ellipse(ctx,a.x,a.y-13,3,5,'#d0c09a')}if(e.type==='stable'){let a=project(e.x-1.2,e.y+1.3);ellipse(ctx,a.x,a.y-8,13,6,'#6b4b35');ctx.fillStyle='#5b4232';ctx.fillRect(a.x+7,a.y-20,5,12);ctx.fillRect(a.x-9,a.y-4,3,8);ctx.fillRect(a.x+6,a.y-4,3,8)}if(e.type==='siege'){let a=project(e.x-1,e.y+1.3);ctx.fillStyle='#9a7849';ctx.fillRect(a.x-16,a.y-12,28,10);ellipse(ctx,a.x-10,a.y,5,6,'#484736');ellipse(ctx,a.x+10,a.y,5,6,'#484736')}}
 if(e.hit>0){ctx.globalAlpha=.15;ellipse(ctx,p.x,p.y-25,s*20,s*15,'#ffcf8b')}ctx.restore()}
function drawNode(n){let p=project(n.x,n.y);if(n.kind==='tree'){let h=37+n.r*33;ellipse(ctx,p.x+8,p.y+3,16+n.r*8,8,'#16392232');ctx.fillStyle='#655c3c';ctx.fillRect(p.x-2,p.y-h*.5,4,h*.5);if(n.r>.45){for(let i=0;i<3;i++){let yy=p.y-h+i*h*.22,ww=12+i*6;poly(ctx,[[p.x,yy],[p.x+ww,yy+h*.47],[p.x-ww,yy+h*.47]],['#294d38','#315940','#3b6344'][i]);poly(ctx,[[p.x,yy],[p.x+ww,yy+h*.47],[p.x+2,yy+h*.39]],'#1c433633')}}else{ellipse(ctx,p.x,p.y-h*.65,19+n.r*10,24,'#34563a');ellipse(ctx,p.x-8,p.y-h*.7,14,17,'#466d43');ellipse(ctx,p.x+7,p.y-h*.78,16,17,'#55794a');ellipse(ctx,p.x-3,p.y-h*.93,12,13,'#62834a');ellipse(ctx,p.x+13,p.y-h*.58,12,13,'#3e6340')}}
 else if(n.kind==='berry'){ellipse(ctx,p.x,p.y,13,7,'#27452955');for(let i=0;i<4;i++){let xx=p.x-10+i*6,yy=p.y-7-Math.sin(i)*5;ellipse(ctx,xx,yy,8,8,i%2?'#506d3a':'#3f6239');for(let j=0;j<3;j++)ellipse(ctx,xx-3+j*3,yy+(j%2)*3,1.6,1.6,'#a85c4b')}}
 else if(n.kind==='deer'){let bob=Math.sin(S.time+n.r*9)*.8;ellipse(ctx,p.x,p.y+1,10,4,'#283f2944');ellipse(ctx,p.x,p.y-9,10,5,'#ad8b58');poly(ctx,[[p.x+5,p.y-10],[p.x+9,p.y-21+bob],[p.x+13,p.y-20+bob],[p.x+10,p.y-7]],'#b69a6c');ctx.strokeStyle='#765f40';ctx.lineWidth=1.5;for(let i of [-6,5]){ctx.beginPath();ctx.moveTo(p.x+i,p.y-7);ctx.lineTo(p.x+i-2,p.y+2);ctx.stroke()}ctx.beginPath();ctx.moveTo(p.x+11,p.y-20);ctx.lineTo(p.x+9,p.y-28);ctx.lineTo(p.x+5,p.y-29);ctx.stroke()}
 else{ellipse(ctx,p.x+3,p.y+2,19,9,'#293f3344');const gold=n.kind==='gold';poly(ctx,[[p.x-18,p.y],[p.x-12,p.y-15],[p.x,p.y-22],[p.x+12,p.y-15],[p.x+18,p.y-2],[p.x+3,p.y+6]],gold?'#81774f':'#89958b','#545e4c');poly(ctx,[[p.x-12,p.y-15],[p.x,p.y-22],[p.x+12,p.y-15],[p.x+1,p.y-9]],gold?'#b6a15a':'#adb5a7');poly(ctx,[[p.x+1,p.y-9],[p.x+12,p.y-15],[p.x+18,p.y-2],[p.x+3,p.y+6]],gold?'#8e854f':'#6e7e76');if(gold)for(let i=0;i<5;i++){let x=p.x-9+i*4,y=p.y-11+(i%2)*7;poly(ctx,[[x,y],[x+4,y-4],[x+6,y],[x+2,y+3]],'#dbb952')}}}
function drawUnit(e){const p=project(e.x,e.y),walk=e.path.length?Math.sin(e.anim*13):0,blue=e.owner?'#bd6353':'#67abc0',dark=e.owner?'#763b36':'#355c70';ellipse(ctx,p.x+2,p.y+1,e.type==='knight'?11:7,e.type==='knight'?5:3,'#18332966');if(selected.includes(e.id)){ctx.strokeStyle='#e7dbaa';ctx.lineWidth=1.3;ctx.beginPath();ctx.ellipse(p.x,p.y+1,e.type==='knight'?14:11,6,0,0,Math.PI*2);ctx.stroke()}
 if(e.type==='trebuchet'){ctx.save();ctx.translate(p.x,p.y);for(let x of [-14,13])ellipse(ctx,x,1,4,6,'#444437');poly(ctx,[[-18,-6],[4,-18],[21,-7],[-1,5]],'#95794d');ctx.strokeStyle='#b69b66';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-12,-6);ctx.lineTo(0,-38);ctx.lineTo(13,-5);ctx.moveTo(0,-38);ctx.lineTo(-15,-56+(e.attackAnim>0?15:0));ctx.moveTo(0,-38);ctx.lineTo(17,-20);ctx.stroke();poly(ctx,[[9,-26],[21,-22],[21,-13],[9,-17]],dark);ctx.strokeStyle='#cbbd8f';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-15,-56);ctx.lineTo(-20,-34);ctx.stroke();ellipse(ctx,-20,-32,4,3,'#7e8370');ctx.restore();return}if(e.type==='ram'){ctx.save();ctx.translate(p.x,p.y);for(let x of [-15,14])ellipse(ctx,x,0,5,7,'#414336');poly(ctx,[[-23,-11],[2,-24],[24,-12],[0,1]],'#826d47');poly(ctx,[[-23,-11],[2,-24],[2,-35],[-23,-22]],'#b09a66');poly(ctx,[[2,-35],[24,-22],[24,-12],[2,-24]],dark);poly(ctx,[[-23,-22],[0,-36],[24,-22],[2,-10]],blue);ctx.strokeStyle='#ceb67c';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-28,-11);ctx.lineTo(29,-11);ctx.stroke();ctx.restore();return}
 let y=p.y;if(e.type==='knight'){ellipse(ctx,p.x,p.y-12,13,7,'#725947');ctx.fillStyle='#594639';ctx.fillRect(p.x+8,p.y-26,5,16);ellipse(ctx,p.x+14,p.y-27,6,4,'#7e6248');ctx.strokeStyle='#453e31';ctx.lineWidth=3;for(let i of [-8,7]){ctx.beginPath();ctx.moveTo(p.x+i,p.y-8);ctx.lineTo(p.x+i+walk*3,p.y+2);ctx.stroke()}y-=12}
 ctx.strokeStyle='#454839';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x-3,y-7);ctx.lineTo(p.x-3-walk*2,y);ctx.moveTo(p.x+3,y-7);ctx.lineTo(p.x+3+walk*2,y);ctx.stroke();poly(ctx,[[p.x-4,y-19],[p.x+4,y-19],[p.x+6,y-6],[p.x-5,y-6]],e.type==='villager'?'#c4b38a':blue);ctx.fillStyle=dark;ctx.fillRect(p.x-4,y-9,9,3);ellipse(ctx,p.x,y-23,3.5,4,'#d4b18a');if(e.type==='villager'){ellipse(ctx,p.x,y-26,6,2,'#a79763');ellipse(ctx,p.x,y-28,3,2,'#c7b681')}else{poly(ctx,[[p.x-4,y-23],[p.x-4,y-28],[p.x+2,y-30],[p.x+5,y-26],[p.x+4,y-23]],'#b0b6a9');ctx.fillStyle=dark;ctx.fillRect(p.x+1,y-25,4,1.5)}let swing=e.work?Math.sin(e.anim*9)*9:e.attackAnim>0?-12:0;ctx.strokeStyle='#d0ae82';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(p.x-3,y-17);ctx.lineTo(p.x-8,y-10+swing*.4);ctx.moveTo(p.x+4,y-17);ctx.lineTo(p.x+9,y-12+swing);ctx.stroke();if(e.type==='archer'){ctx.strokeStyle='#b7965d';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x+6,y-17,10,-1.2,1.2);ctx.stroke();ctx.strokeStyle='#d7c795';ctx.beginPath();ctx.moveTo(p.x+10,y-26);ctx.lineTo(p.x+10,y-8);ctx.stroke()}else if(e.type!=='villager'){ctx.strokeStyle='#d2d5bd';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x+8,y-12+swing);ctx.lineTo(p.x+13,y-29+swing);ctx.stroke();ellipse(ctx,p.x-7,y-13,4,6,blue);ctx.strokeStyle='#d3c697';ctx.lineWidth=1;ctx.stroke()}else if(e.work){ctx.strokeStyle='#826540';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x+8,y-11+swing);ctx.lineTo(p.x+14,y-24+swing);ctx.stroke();ctx.fillStyle='#a6ac95';ctx.fillRect(p.x+11,y-25+swing,8,3)}if(e.hit>0){ellipse(ctx,p.x,y-13,6,8,'#efc28666')}}
function render(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#253e31';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2-cam.x*cam.zoom,H*.48-cam.y*cam.zoom);ctx.scale(cam.zoom,cam.zoom);ctx.drawImage(terrainCanvas,-N*TW/2-64,-50);
 // Soft edge shadows and mist over the unexplored land.
 const corners=[unproject(-150,0),unproject(W+150,0),unproject(0,H+150),unproject(W+150,H+150)];const minX=clamp(Math.floor(Math.min(...corners.map(p=>p.x))),0,N-1),maxX=clamp(Math.ceil(Math.max(...corners.map(p=>p.x))),0,N-1),minY=clamp(Math.floor(Math.min(...corners.map(p=>p.y))),0,N-1),maxY=clamp(Math.ceil(Math.max(...corners.map(p=>p.y))),0,N-1);
 for(let id of selected){let e=byId(id);if(e?.building){let p=project(e.x,e.y),s=DATA[e.type].size;ctx.strokeStyle='#e1d49b';ctx.lineWidth=1.8;let a=project(e.x-s/2-.15,e.y-s/2-.15),b=project(e.x+s/2+.15,e.y-s/2-.15),c=project(e.x+s/2+.15,e.y+s/2+.15),d=project(e.x-s/2-.15,e.y+s/2+.15);poly(ctx,[[a.x,a.y],[b.x,b.y],[c.x,c.y],[d.x,d.y]],'#dfd2a211','#e3d5a1');if(e.rally){let q=project(e.rally.x,e.rally.y);ctx.setLineDash([4,5]);ctx.strokeStyle='#d0c79066';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.setLineDash([]);flag(e.rally.x,e.rally.y,32,0)}}}
 const list=[...nodes.filter(n=>n.amount>0&&S.explored[idx(n.x,n.y)]),...entities.filter(e=>e.hp>0&&(e.owner===0||e.building?S.explored[idx(e.x,e.y)]:S.visible[idx(e.x,e.y)]))].filter(e=>e.x>=minX-3&&e.x<=maxX+3&&e.y>=minY-3&&e.y<=maxY+3).sort((a,b)=>(a.x+a.y)-(b.x+b.y));
 for(let e of list){if(e.kind)drawNode(e);else if(e.building)drawBuilding(e);else drawUnit(e);if(!e.kind&&(selected.includes(e.id)||e.hp<e.maxHp||e.progress<1)){let p=project(e.x,e.y),bw=e.building?44:24,yy=p.y-(e.building?DATA[e.type].size*24+30:e.type==='knight'?48:35);ctx.fillStyle='#15291bdc';ctx.fillRect(p.x-bw/2-1,yy-1,bw+2,5);ctx.fillStyle=e.progress<1?'#d8b768':e.owner?'#be6b58':'#9abc78';ctx.fillRect(p.x-bw/2,yy,bw*(e.progress<1?e.progress:Math.max(0,e.hp/e.maxHp)),3)}}
 for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){if(S.visible[idx(x,y)])continue;let p=project(x,y);poly(ctx,[[p.x,p.y],[p.x+32.5,p.y+16],[p.x,p.y+32.5],[p.x-32.5,p.y+16]],S.explored[idx(x,y)]?'#15281e65':'#182d29e8')}
 for(let f of effects){let p=project(f.x,f.y),a=f.life/f.max;if(f.kind==='ring'){ctx.strokeStyle=f.color;ctx.lineWidth=2*a;ctx.beginPath();ctx.ellipse(p.x,p.y,22*(1-a)+5,11*(1-a)+3,0,Math.PI*2);ctx.stroke()}else if(f.kind==='arrow'||f.kind==='stone'){let q=project(f.tx,f.ty),t=1-a;let xx=p.x+(q.x-p.x)*t,yy=p.y-f.fromHeight+(q.y-p.y+f.fromHeight-15)*t-Math.sin(t*Math.PI)*25;if(f.kind==='stone')ellipse(ctx,xx,yy,4,4,'#bcb8a1');ctx.strokeStyle='#eadbc0';ctx.lineWidth=1.8;ctx.beginPath();ctx.moveTo(xx,yy);ctx.lineTo(xx-(q.x-p.x)*.05,yy-(q.y-p.y)*.05+4);ctx.stroke()}else if(f.kind==='death'){for(let i=0;i<5;i++)ellipse(ctx,p.x+Math.sin(i*5)*(1-a)*25,p.y-i*4-(1-a)*20,(f.building?14:5)*(1-a)+2,(f.building?10:4)*(1-a)+2,`rgba(181,155,104,${a*.4})`)}}
 if(placement){let w=unproject(mouse.x,mouse.y),x=Math.round(w.x),y=Math.round(w.y),ok=validSite(placement,x,y)&&S.visible[idx(x,y)]&&afford(DATA[placement].cost);let s=DATA[placement].size,a=project(x-s/2,y-s/2),b=project(x+s/2,y-s/2),c=project(x+s/2,y+s/2),d=project(x-s/2,y+s/2);poly(ctx,[[a.x,a.y],[b.x,b.y],[c.x,c.y],[d.x,d.y]],ok?'#b4d29b66':'#c75c5166',ok?'#d4e4ad':'#ef8b6b');drawBuilding({x,y,type:placement,owner:0,progress:1},true)}
 ctx.restore();renderMinimap();}
function renderMinimap(){const mw=mini.width,mh=mini.height,sx=mw/N,sy=mh/N;mc.fillStyle='#16261f';mc.fillRect(0,0,mw,mh);for(let t of terrain){if(!S.explored[idx(t.x,t.y)])continue;mc.fillStyle=t.type==='water'?'#427d78':t.type==='road'?'#8c885b':S.visible[idx(t.x,t.y)]?'#63794b':'#354d38';mc.fillRect(t.x*sx,t.y*sy,sx+.4,sy+.4)}for(let n of nodes){if(n.amount<=0||!S.explored[idx(n.x,n.y)])continue;mc.fillStyle=n.kind==='tree'?'#304f35':n.kind==='gold'?'#d3b05c':n.kind==='berry'?'#996d60':'#a4ad90';mc.fillRect(n.x*sx,n.y*sy,2,2)}for(let e of entities){if(e.hp<=0||e.owner&&!(e.building?S.explored[idx(e.x,e.y)]:S.visible[idx(e.x,e.y)]))continue;mc.fillStyle=e.owner?'#da785e':'#85d1de';let z=e.building?DATA[e.type].size:1;mc.fillRect((e.x-z/2)*sx,(e.y-z/2)*sy,Math.max(2,z*sx),Math.max(2,z*sy))}let c=[unproject(0,76),unproject(W,76),unproject(W,H-220),unproject(0,H-220)];mc.strokeStyle='#e7dfb59c';mc.lineWidth=1;mc.beginPath();c.forEach((p,i)=>i?mc.lineTo(p.x*sx,p.y*sy):mc.moveTo(p.x*sx,p.y*sy));mc.closePath();mc.stroke()}
let buildPage=-1,lastSelection='';
function buttonAction(name,icon,fn,desc='',cost=null,hotkey='',locked=false,badge=''){let b=document.createElement('button');b.className='action'+(locked?' locked':'');b.setAttribute('aria-label',name);b.innerHTML=`<span class="hotkey">${hotkey}</span><span class="icon">${icon}</span><span class="action-name">${name}</span>${badge?`<span class="badge">${badge}</span>`:''}`;b.addEventListener('click',()=>{if(locked){notify('Advance to the required age to unlock this.',true);return}fn()});b.addEventListener('mouseenter',()=>{let tt=$('#tooltip');tt.innerHTML=`<strong>${name}</strong>${cost?`<div class="costs">${costText(cost)}</div>`:''}<p>${desc}</p>${locked?'<p>Requires a later age</p>':''}`;tt.classList.remove('hidden');let r=b.getBoundingClientRect();tt.style.left=clamp(r.left,10,W-225)+'px';tt.style.top=r.top-tt.offsetHeight-12+'px'});b.addEventListener('mouseleave',()=>$('#tooltip').classList.add('hidden'));$('#actions').append(b)}
function setPlacement(type){if(!afford(DATA[type].cost)){notify('Not enough resources. '+costText(DATA[type].cost),true);return}placement=type;commandMode=null;$('#placementHint').textContent=`Place ${DATA[type].name} · Click to build · Esc to cancel`;$('#placementHint').classList.remove('hidden');$('#tooltip').classList.add('hidden');canvas.style.cursor='crosshair'}
function cancelMode(){placement=null;commandMode=null;$('#placementHint').classList.add('hidden');canvas.style.cursor='default'}
function updateUI(force=false){if(!S)return;const r=S.resources[0];$('#resources').innerHTML=['food','wood','gold','stone'].map(k=>{let workers=entities.filter(e=>e.owner===0&&e.hp>0&&e.task?.kind==='gather'&&e.task.resource===k).length;return`<div class="resource" title="${k}: ${workers} villagers gathering"><span class="resource-icon" style="color:${k==='gold'?'#d9b564':k==='stone'?'#a7b4ae':''}">${icons[k]}</span><div><strong>${Math.floor(r[k])}<span class="workers">${workers?'+'+workers:''}</span></strong><small>${k.toUpperCase()}</small></div></div>`}).join('')+`<div class="resource" title="Population / capacity"><span class="resource-icon" style="color:#bcb8a1">♟</span><div><strong style="${population(0)>=cap(0)?'color:#dd9278':''}">${population(0)}<span style="font-size:12px;color:#879881"> / ${cap(0)}</span></strong><small>POPULATION</small></div></div>`;
 $('#ageName').textContent=AGES[S.age[0]];$('.age-gem').textContent=['I','II','III','IV'][S.age[0]];$('#advance').innerHTML=S.research?.kind==='age'?`${Math.ceil(S.research.left)}s remaining`:S.age[0]===3?'Golden era ✦':'Advance age <span>↗</span>';$('#advance').disabled=!!S.research||S.age[0]===3;$('#advance').title=S.age[0]===0?'Feudal Age: 450 food, 150 gold · 40 seconds':S.age[0]===1?'Castle Age: 750 food, 400 gold · 55 seconds':'Imperial Age: 1000 food, 700 gold · 55 seconds';$('.age-progress').style.width=S.research?(1-S.research.left/S.research.total)*100+'%':'0';$('#clock').textContent=`${String(Math.floor(S.time/60)).padStart(2,'0')}:${String(Math.floor(S.time%60)).padStart(2,'0')}`;$('#rivalState').textContent=S.time>S.nextRaid-25?'Preparing a raid':S.age[1]===3?'Imperial Age':S.age[1]===2?'Castle Age':S.age[1]===1?'Feudal Age':'Gathering strength';
 const goals=[['Grow to 12 villagers',count(0,'villager')>=12,`${Math.min(12,count(0,'villager'))}/12`],['Raise a barracks',count(0,'barracks')>0,''],['Reach the Feudal Age',S.age[0]>=1,''],['Defeat House Raven',ended&&count(1,'town')===0,'']];$('#objectiveList').innerHTML=goals.map(([text,done,n])=>`<div class="objective ${done?'done':''}"><span class="check">${done?'✓':''}</span><span>${text}</span><span style="margin-left:auto;color:#93a284">${n}</span></div>`).join('');
 selected=selected.filter(id=>byId(id));const es=selected.map(byId),e=es[0],signature=selected.join(',')+'-'+S.age[0]+'-'+buildPage+'-'+(e?.progress>=1)+'-'+S.upgrades[0].attack+S.upgrades[0].armor;$('#selectionName').textContent=es.length>1?`${es.length} units selected`:e?e.kind?({tree:'Woodline',berry:'Berry bushes',gold:'Gold deposit',stone:'Stone deposit',deer:'Wild deer'}[e.kind]):DATA[e.type].name:'Your kingdom';$('#selectionOwner').textContent=e?.owner===1?'HOUSE RAVEN':e?.kind?'THE GREEN MARCHES':'YOUR KINGDOM';$('#portrait').textContent=es.length>1?'⚔':e?e.kind?icons[e.resource]||'♧':DATA[e.type].icon:'♛';$('#selectionDetails').innerHTML=es.length>1?`${es.filter(e=>e.type==='villager').length} workers · ${es.filter(e=>e.type!=='villager').length} soldiers`:e?.kind?`${Math.ceil(e.amount)} ${e.resource||'wildlife'}`:e?`${Math.ceil(e.hp)} / ${e.maxHp} health<br>${e.progress<1?'Under construction':e.building?(e.queue.length?'Training in progress':'Building · '+AGES[S.age[0]]):e.task?({gather:'Gathering '+e.task.resource,build:'Building',attack:'In combat',move:'Moving',attackMove:'Advancing',repair:'Repairing'}[e.task.kind]||'Ready'):'Ready for orders'}`:'Select a unit or building<br>to issue your command.';$('#health span').style.width=(e?.hp?e.hp/e.maxHp*100:0)+'%';$('#queueLabel').textContent=e?.queue?.length?`${DATA[e.queue[0].type].name} · ${Math.ceil(e.queue[0].left)}s · ${e.queue.length} queued`:'';
 if(!force&&signature===lastSelection)return;lastSelection=signature;$('#actions').innerHTML='';$('#tooltip').classList.add('hidden');$('#actionLabel').textContent=e?.owner===1?'RIVAL KINGDOM':e?.kind?'NATURAL RESOURCES':buildPage>=0?'BUILD YOUR SETTLEMENT':e?es.length>1?'GROUP COMMANDS':DATA[e.type].name.toUpperCase():'KINGDOM COMMANDS';$('#contextHint').textContent='Right-click the ground to move. Drag to select a group.';
 if(!e){buttonAction('Town Center','♜',goHome,'Select and return to your Town Center.',null,'H');buttonAction('Idle workers','♟',selectIdle,'Select all villagers waiting for an assignment.',null,'.');buttonAction('Field guide','?',openGuide,'Learn to build, advance and conquer.');return}if(e.owner===1){$('#contextHint').textContent='Select your soldiers and right-click this enemy to attack.';return}if(e.kind){$('#contextHint').textContent='Select a villager and right-click this deposit to gather.';return}
 if(es.some(e=>e.type==='villager')){if(buildPage>=0){let types=buildPage===0?['house','farm','barracks','range','tower']:['blacksmith','stable','siege','castle'];for(let type of types){let d=DATA[type];buttonAction(d.name,d.icon,()=>setPlacement(type),d.desc,d.cost,'',(d.age||0)>S.age[0])}buttonAction(buildPage===0?'More buildings':'Essentials','↔',()=>{buildPage=1-buildPage;updateUI(true)},'Browse more construction options.');buttonAction('Back','↩',()=>{buildPage=-1;updateUI(true)});$('#contextHint').textContent='Choose a building, then place it on clear ground. Right-click to cancel.'}else{buttonAction('Construct','⚒',()=>{buildPage=0;updateUI(true)},'Open the construction menu.',null,'B');buttonAction('Stop','■',stopSelected,'Cancel orders for all selected units.');buttonAction('Idle workers','♟',selectIdle,'Select idle villagers.',null,'.');buttonAction('Town Center','♜',goHome,'Return to the heart of your kingdom.',null,'H');$('#contextHint').textContent='Right-click trees, berries, gold or stone to gather. Right-click buildings to build or repair.'}}
 else if(e.building){if(e.progress<1){buttonAction('Cancel build','×',()=>{for(let[k,v]of Object.entries(DATA[e.type].cost||{}))r[k]+=v*.7;e.hp=0;selected=[];updateUI(true)},'Cancel construction and recover 70% of its cost.');$('#contextHint').textContent='Assign additional villagers to finish construction faster.'}else{for(let type of DATA[e.type].train||[]){let d=DATA[type];buttonAction(d.name,d.icon,()=>train(e,type),d.desc+` Training time: ${d.time}s.`,d.cost,'',d.age>S.age[0])}if(e.type==='blacksmith')for(let kind of ['attack','armor'])buttonAction(kind==='attack'?'Forged weapons':'Reinforced armor',kind==='attack'?'⚔':'⛨',()=>upgrade(kind),`Improves every soldier. Current level ${S.upgrades[0][kind]}.`,{food:120+S.upgrades[0][kind]*90,gold:100+S.upgrades[0][kind]*80},'',S.upgrades[0][kind]>=S.age[0],S.upgrades[0][kind]);if(e.type==='town')buttonAction('Idle workers','♟',selectIdle,'Select villagers waiting for work.',null,'.');if(e.queue.length)buttonAction('Cancel last','×',()=>{let q=e.queue.pop();for(let[k,v]of Object.entries(DATA[q.type].cost))r[k]+=v;updateUI(true)},'Remove the last queued unit and refund its cost.');$('#contextHint').textContent=DATA[e.type].train?'Click to train units. Right-click the ground to set a rally point.':DATA[e.type].desc}}
 else{buttonAction('Attack move','⚔',()=>{commandMode='attackMove';$('#placementHint').textContent='Attack move · Click a destination · Esc to cancel';$('#placementHint').classList.remove('hidden');canvas.style.cursor='crosshair'},'Move toward a destination, fighting enemies along the way.',null,'Q');buttonAction('Stop','■',stopSelected,'Stop moving. Soldiers still defend themselves.');buttonAction('Select army','⚑',selectArmy,'Select all your soldiers on the map.');$('#contextHint').textContent='Right-click an enemy to attack. Use Attack move to engage enemies along a route.'}}
function stopSelected(){for(let e of selected.map(byId).filter(Boolean)){e.task=null;e.path=[];e.resume=null}cancelMode();updateUI(true)}function selectIdle(){selected=entities.filter(e=>e.hp>0&&e.owner===0&&e.type==='villager'&&!e.task).map(e=>e.id);buildPage=-1;if(!selected.length)notify('All villagers have work.');else{center(byId(selected[0]));notify(`${selected.length} idle villagers selected.`)}updateUI(true)}function selectArmy(){selected=entities.filter(e=>e.hp>0&&!e.owner&&!e.building&&e.type!=='villager').map(e=>e.id);buildPage=-1;updateUI(true)}function center(e){if(!e)return;let p=project(e.x,e.y);cam.x=p.x;cam.y=p.y}function goHome(){let e=entities.find(e=>e.hp>0&&!e.owner&&e.type==='town');if(e){center({x:e.x+1,y:e.y-1});selected=[e.id];buildPage=-1;updateUI(true)}}
function hitTest(x,y){let w=unproject(x,y);const candidates=entities.filter(e=>e.hp>0&&(e.owner===0||S.visible[idx(e.x,e.y)])).sort((a,b)=>(b.x+b.y)-(a.x+a.y));for(let e of candidates.filter(e=>!e.building)){let p=screen(e.x,e.y);if(Math.abs(x-p.x)<14*cam.zoom&&y<p.y+8*cam.zoom&&y>p.y-38*cam.zoom)return e}for(let e of candidates.filter(e=>e.building)){let p=screen(e.x,e.y),s=DATA[e.type].size;if(Math.abs(w.x-e.x)<s/2&&Math.abs(w.y-e.y)<s/2||Math.abs(x-p.x)<s*16*cam.zoom&&y<p.y&&y>p.y-(s*22+25)*cam.zoom)return e}const ns=nodes.filter(n=>n.amount>0&&S.visible[idx(n.x,n.y)]).sort((a,b)=>dist(a,w)-dist(b,w));return ns.find(n=>{let p=screen(n.x,n.y);return dist(n,w)<.9||n.kind==='tree'&&Math.abs(x-p.x)<18*cam.zoom&&y<p.y&&y>p.y-55*cam.zoom})}
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(!started||paused)return;mouse={x:e.clientX,y:e.clientY};if(e.button===1){pan={x:e.clientX,y:e.clientY,cx:cam.x,cy:cam.y};canvas.setPointerCapture(e.pointerId);return}if(e.button===2){if(placement||commandMode){cancelMode();return}commandAt(unproject(e.clientX,e.clientY),hitTest(e.clientX,e.clientY));return}if(e.button!==0)return;if(placement){let p=unproject(e.clientX,e.clientY),x=Math.round(p.x),y=Math.round(p.y);if(!S.visible[idx(x,y)]){notify('Explore this land before building.',true);return}let builders=selected.map(byId).filter(e=>e?.type==='villager'&&e.owner===0);if(!builders.length){cancelMode();return}let b=place(placement,x,y,0,builders);if(!b){notify('Choose clear ground with enough space.',true);return}if(!e.shiftKey)cancelMode();updateUI(true);return}if(commandMode){commandAt(unproject(e.clientX,e.clientY),hitTest(e.clientX,e.clientY));cancelMode();return}drag={x:e.clientX,y:e.clientY,shift:e.shiftKey};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{mouse={x:e.clientX,y:e.clientY};if(pan){cam.x=pan.cx-(e.clientX-pan.x)/cam.zoom;cam.y=pan.cy-(e.clientY-pan.y)/cam.zoom;return}if(drag&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5){let el=$('#selectionBox');el.style.display='block';el.style.left=Math.min(drag.x,e.clientX)+'px';el.style.top=Math.min(drag.y,e.clientY)+'px';el.style.width=Math.abs(drag.x-e.clientX)+'px';el.style.height=Math.abs(drag.y-e.clientY)+'px'}});
canvas.addEventListener('pointerup',e=>{pan=null;if(!drag)return;let movement=Math.hypot(e.clientX-drag.x,e.clientY-drag.y);if(movement>5){let units=entities.filter(en=>{if(en.owner!==0||en.hp<=0||en.building)return false;let p=screen(en.x,en.y);return p.x>=Math.min(drag.x,e.clientX)&&p.x<=Math.max(drag.x,e.clientX)&&p.y>=Math.min(drag.y,e.clientY)&&p.y<=Math.max(drag.y,e.clientY)}).map(e=>e.id);selected=drag.shift?[...new Set([...selected,...units])]:units}else{let en=hitTest(e.clientX,e.clientY);if(en){if(drag.shift){selected=selected.includes(en.id)?selected.filter(id=>id!==en.id):[...selected,en.id]}else selected=[en.id];tone(430,.035)}else selected=[]}drag=null;$('#selectionBox').style.display='none';buildPage=-1;updateUI(true)});
canvas.addEventListener('dblclick',e=>{if(paused)return;let en=hitTest(e.clientX,e.clientY);if(en&&!en.building&&en.owner===0&&!en.kind){selected=entities.filter(u=>u.type===en.type&&u.owner===0&&u.hp>0&&dist(u,en)<17).map(u=>u.id);updateUI(true)}});
canvas.addEventListener('wheel',e=>{e.preventDefault();const before=unproject(e.clientX,e.clientY);cam.zoom=clamp(cam.zoom*(e.deltaY>0?.9:1.1),.45,1.65);const after=unproject(e.clientX,e.clientY),a=project(before.x,before.y),b=project(after.x,after.y);cam.x+=a.x-b.x;cam.y+=a.y-b.y},{passive:false});
mini.addEventListener('pointerdown',e=>{if(!started)return;let r=mini.getBoundingClientRect(),p={x:(e.clientX-r.left)/r.width*N,y:(e.clientY-r.top)/r.height*N};if(e.button===2)commandAt(p,null);else center(p)});mini.addEventListener('contextmenu',e=>e.preventDefault());
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(!started)return;if(e.code==='Escape'){cancelMode();buildPage=-1;$('#guideModal').classList.add('hidden');if(!$('#pauseModal').classList.contains('hidden'))togglePause(false);else if(paused&&!ended)paused=false;updateUI(true);return}if(e.code==='Space'&&!e.repeat){togglePause();return}if(paused)return;if(e.code==='KeyQ'&&selected.some(id=>{let u=byId(id);return u&&!u.building&&u.type!=='villager'&&u.owner===0})){commandMode='attackMove';$('#placementHint').textContent='Attack move · Click a destination · Esc to cancel';$('#placementHint').classList.remove('hidden');canvas.style.cursor='crosshair'}if(e.code==='KeyH')goHome();if(e.code==='Period')selectIdle();if(e.code==='KeyB'&&selected.some(id=>byId(id)?.type==='villager')){buildPage=0;updateUI(true)}if(e.code==='KeyA'&&!e.repeat&&e.shiftKey){selectArmy();keys.KeyA=false}if(e.code==='Delete'&&selected.length&&confirm('Disband or demolish the selected units and buildings?')){for(let en of selected.map(byId).filter(en=>en?.owner===0))en.hp=0;selected=[];checkEnd();updateUI(true)}if(/^Digit[1-9]$/.test(e.code)){let n=e.code.at(-1);if(e.ctrlKey||e.metaKey){e.preventDefault();controlGroups[n]=[...selected];notify(`Control group ${n} assigned.`)}else{selected=(controlGroups[n]||[]).filter(id=>byId(id));buildPage=-1;updateUI(true)}}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('blur',()=>keys={});
function togglePause(value){if(!started||ended)return;paused=value??!paused;$('#pauseModal').classList.toggle('hidden',!paused);$('#pause').textContent=paused?'▶':'Ⅱ'}function openGuide(){if(started)paused=true;$('#guideModal').classList.remove('hidden')}$('#pause').onclick=()=>togglePause();$('#resume').onclick=()=>togglePause(false);$('#help').onclick=openGuide;$('#closeGuide').onclick=()=>{$('#guideModal').classList.add('hidden');if(started)paused=ended||!$('#pauseModal').classList.contains('hidden')};$('#home').onclick=goHome;$('#advance').onclick=()=>{if(!paused)advanceAge()};$('#sound').onclick=()=>{soundOn=!soundOn;$('#sound').style.opacity=soundOn?'1':'.4';if(soundOn)tone(600,.15)};
function saveGame(show=true){if(ended)return;try{localStorage.setItem('crown-save',JSON.stringify({version:1,S,nodes,entities,cam,nextId,controlGroups}));if(show)notify('Your kingdom has been saved.')}catch{if(show)notify('Unable to save in this browser.',true)}}$('#save').onclick=()=>saveGame();
function restart(){if(!confirm('Start a new campaign? Your current local save will be replaced.'))return;localStorage.removeItem('crown-save');location.reload()}$('#restart').onclick=restart;$('#playAgain').onclick=()=>{localStorage.removeItem('crown-save');location.reload()};$('#continue').onclick=()=>{$('#endModal').classList.add('hidden');paused=false};
$$('[data-difficulty]').forEach(b=>b.onclick=()=>{difficulty=b.dataset.difficulty;$$('[data-difficulty]').forEach(a=>a.classList.toggle('active',a===b))});
let saved=null;try{saved=JSON.parse(localStorage.getItem('crown-save'));if(saved?.version!==1)saved=null}catch{}generate();if(saved){$('#begin').innerHTML='Continue your kingdom <span>→</span>';$('.intro-foot').innerHTML=`Saved campaign · ${AGES[saved.S.age[0]]} · ${Math.floor(saved.S.time/60)} minutes <button id="fresh" style="font-size:9px;padding:2px 5px;margin-left:8px">New campaign</button>`;$('#fresh').onclick=()=>{saved=null;localStorage.removeItem('crown-save');$('#begin').innerHTML='Establish your kingdom <span>→</span>';$('.intro-foot').textContent='A complete skirmish · 15–25 minutes · Autosaved locally'}}
$('#begin').onclick=()=>{try{audioCtx=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume()}catch{}if(saved){S=saved.S;nodes=saved.nodes;entities=saved.entities;cam=saved.cam;nextId=saved.nextId;controlGroups=saved.controlGroups||{};difficulty=S.difficulty;selected=[];updateVision();goHome()}else generate();started=true;paused=false;$('#modal').classList.add('hidden');notify('Your villagers are gathering. Train more at the Town Center.');setTimeout(()=>{if(S.time<80)notify('Build a barracks, raise an army, and seek House Raven to the northeast.')},9000);tone(440,.4);updateUI(true)};
function frame(ts){let dt=Math.min(.05,(ts-last)/1000||0);last=ts;if(started&&!paused){let speed=550*dt/cam.zoom;if(keys.KeyW||keys.ArrowUp)cam.y-=speed;if(keys.KeyS||keys.ArrowDown)cam.y+=speed;if(keys.KeyA||keys.ArrowLeft)cam.x-=speed;if(keys.KeyD||keys.ArrowRight)cam.x+=speed;cam.x=clamp(cam.x,-N*TW/2,N*TW/2);cam.y=clamp(cam.y,80,N*TH-80);update(dt)}uiTick+=dt;if(uiTick>.3){updateUI();uiTick=0}render();requestAnimationFrame(frame)}requestAnimationFrame(frame);
// Read-only inspection and deterministic simulation hooks for browser verification.
window.__game={get state(){return S},get entities(){return entities},get nodes(){return nodes},get selected(){return selected},get paused(){return paused},get camera(){return cam},project:screen,world:unproject,select(ids){selected=ids;buildPage=-1;updateUI(true)},step(seconds){for(let t=0;t<seconds;t+=.1)update(Math.min(.1,seconds-t));updateUI(true)},command:commandAt,train,place,advanceAge,save:saveGame,center,validSite,refresh:()=>updateUI(true)};
