import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:900}});await page.goto('http://localhost:4173');await page.click('#begin');
 await page.evaluate(()=>{__game.state.age[0]=2;Object.assign(__game.state.resources[0],{food:1300,wood:3000,gold:1500,stone:1000});__game.refresh()});await page.click('#advance');await page.evaluate(()=>__game.step(56));assert.equal(await page.evaluate(()=>__game.state.age[0]),3);console.log('PASS Imperial Age');
 const siege=await page.evaluate(()=>{let v=__game.entities.find(e=>e.owner===0&&e.type==='villager');for(let y=25;y<42;y++)for(let x=14;x<27;x++)if(__game.validSite('siege',x,y)){let b=__game.place('siege',x,y,0,[v]);__game.step(55);return {id:b.id,progress:b.progress}}});assert.equal(siege.progress,1);await page.evaluate(id=>__game.select([id]),siege.id);await page.getByRole('button',{name:'Trebuchet',exact:true}).click();await page.evaluate(()=>__game.step(36));assert(await page.evaluate(()=>__game.entities.some(e=>e.type==='trebuchet'&&e.owner===0)));console.log('PASS siege workshop and trebuchet training');
 const hit=await page.evaluate(()=>{let ram=__game.entities.find(e=>e.type==='trebuchet'&&!e.owner);let t=__game.entities.find(e=>e.owner===1&&e.type==='town');ram.x=t.x-11;ram.y=t.y;ram.path=[];__game.select([ram.id]);let before=t.hp;__game.command(t,t);__game.step(6);return {before,after:t.hp,hp:ram.hp}});assert(hit.after<hit.before);assert.equal(hit.hp,180);console.log('PASS trebuchet outranges Town Center',hit);
 // A fresh, undefended campaign must eventually be defeated by the actual AI.
 await page.evaluate(()=>localStorage.clear());await page.reload();await page.click('#begin');await page.evaluate(()=>__game.step(1200));let result=await page.evaluate(()=>({time:__game.state.time,age:__game.state.age[1],raids:__game.state.raid,town:__game.entities.find(e=>e.owner===0&&e.type==='town').hp,pop:__game.entities.filter(e=>e.owner===0&&e.hp>0&&!e.building).length}));console.log('Natural campaign',result);assert(result.raids>=2);assert(result.town<=0);assert.match(await page.locator('#endTitle').innerText(),/remembered/);console.log('PASS AI can win a complete campaign');
}finally{await browser.close()}
