import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined),headless:true});
const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1});
const page=await context.newPage();const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const base=process.env.GAME_URL||'http://localhost:4173';
const result=[];
async function test(name,fn){await fn();result.push(name);console.log('✓ '+name);}
async function sim(seconds){await page.evaluate(seconds=>{const g=__CROWN.game;const paused=g.paused;g.paused=false;__CROWN.step(seconds);g.paused=paused;__CROWN.refresh(true);},seconds);}
async function state(fn){return page.evaluate(fn);}
try{
await context.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
await page.goto(base);await page.waitForFunction(()=>window.__CROWN);await page.evaluate(()=>{__CROWN.game.paused=true;__CROWN.refresh(true);});
await test('Loads the game, renders the battlefield, and displays starting resources',async()=>{assert.match(await page.title(),/Crown & Conquest/);assert.equal(await page.locator('#selectionName').textContent(),'Town Center');assert.equal(await page.locator('.resource').count(),5);assert.equal(await state(()=>__CROWN.game.population()),10);});
await test('Production button queues a villager and updates the cost and queue',async()=>{const food=await state(()=>__CROWN.game.players[0].resources.food);await page.locator('[data-action="train:villager"]').click();assert.equal(await state(()=>__CROWN.game.players[0].resources.food),food-50);assert.equal(await page.locator('.queue-slot.filled').count(),1);await sim(13);assert.equal(await state(()=>__CROWN.game.population()),11);});
await test('Queue cancel refunds resources through the interface',async()=>{const food=await state(()=>__CROWN.game.players[0].resources.food);await page.locator('[data-action="train:villager"]').click();await page.locator('[data-queue="0"]').click();assert.equal(await state(()=>__CROWN.game.players[0].resources.food),food);});
await test('Tooltips explain costs and age requirements',async()=>{await page.locator('[data-action="tech:wheelbarrow"]').hover();assert.equal(await page.locator('#tooltip').isVisible(),true);assert.match(await page.locator('#tooltip').textContent(),/Feudal Age/);});
await test('Idle villager selection opens building commands, and a placed house completes',async()=>{
  await page.locator('#idleButton').click();assert.equal(await page.locator('#selectionName').textContent(),'Villager');
  const site=await state(()=>{const {game:g,renderer:r}=__CROWN;let best=null,d=Infinity;const w=g.getSelected()[0];for(let x=4;x<23;x++)for(let y=6;y<28;y++){const p=r.toScreen(x,y);if(p.x>310&&p.x<1120&&p.y>65&&p.y<r.height-80&&g.canPlace('house',x,y)){const score=Math.hypot(x-w.x,y-w.y);if(score<d){d=score;best={x,y,sx:p.x,sy:p.y};}}}return best;});assert.ok(site);
  await page.locator('[data-action="build:house"]').click();assert.equal(await page.locator('#placementHint').isVisible(),true);
  const rect=await page.locator('#world').boundingBox();await page.mouse.click(rect.x+site.sx,rect.y+site.sy);assert.equal(await state(()=>__CROWN.game.own(0,'building').filter(b=>!b.complete).length),1);await sim(40);assert.equal(await state(()=>__CROWN.game.capacity()),25);
});
await test('Right-click orders a villager to gather and deposits resources',async()=>{
  const target=await state(()=>{const {game:g,renderer:r}=__CROWN;const e=g.entities.find(e=>e.kind==='resource'&&e.resource==='gold'&&g.isVisible(e));r.focus(e);const p=r.toScreen(e.x,e.y,8);return{id:e.id,x:p.x,y:p.y};});
  const rect=await page.locator('#world').boundingBox();await page.mouse.click(rect.x+target.x,rect.y+target.y,{button:'right'});assert.equal(await state(()=>__CROWN.game.getSelected()[0].order.type),'gather');const gold=await state(()=>__CROWN.game.players[0].resources.gold);await sim(35);assert.ok(await state(()=>__CROWN.game.players[0].resources.gold)>gold);
});
await test('Age advancement unlocks new buildings and units',async()=>{await page.keyboard.press('h');await page.evaluate(()=>{__CROWN.game.players[0].resources.food=900;__CROWN.game.players[0].resources.gold=500;__CROWN.refresh(true);});await page.locator('[data-action="age"]').click();await sim(42);assert.equal(await page.locator('#ageName').textContent(),'Feudal Age');await page.keyboard.press('b');await page.locator('[data-tab="military"]').click();assert.equal(await page.locator('[data-action="build:range"]').getAttribute('data-age'),'1');assert.equal(await page.locator('[data-action="build:range"]').getAttribute('aria-disabled'),'false');});
await test('Army selection, move commands, and stop controls work',async()=>{await page.locator('#armyButton').click();assert.equal(await state(()=>__CROWN.game.selected.length),3);await page.locator('[data-action="move"]').click();const rect=await page.locator('#world').boundingBox();await page.mouse.click(rect.x+800,rect.y+450);assert.ok(await state(()=>__CROWN.game.getSelected().every(u=>u.order.type==='move')));await sim(4);await page.locator('[data-action="stop"]').click();assert.ok(await state(()=>__CROWN.game.getSelected().every(u=>u.order.type==='idle')));});
await test('Camera zoom, minimap navigation, and town-center shortcut work',async()=>{const zoom=await state(()=>__CROWN.renderer.camera.zoom);await page.locator('#zoomIn').click();assert.ok(await state(()=>__CROWN.renderer.camera.zoom)>zoom);await page.locator('#minimap').click({position:{x:120,y:100}});const old=await state(()=>__CROWN.renderer.camera.y);await page.keyboard.press('h');assert.notEqual(await state(()=>__CROWN.renderer.camera.y),old);assert.equal(await page.locator('#selectionName').textContent(),'Town Center');});
await test('Pause and speed controls are reversible',async()=>{await page.locator('#pauseButton').click();assert.equal(await state(()=>__CROWN.game.paused),false);await page.keyboard.press('Space');assert.equal(await state(()=>__CROWN.game.paused),true);await page.locator('#speedButton').click();assert.equal(await state(()=>__CROWN.game.speed),1.5);});
await test('Menu saves and restores the current kingdom',async()=>{await page.locator('#menuButton').click();await page.locator('[data-modal-action="save"]').click();const saved=await state(()=>JSON.parse(localStorage.getItem('crown-conquest-save-v1')).players[0].resources.wood);await page.evaluate(()=>__CROWN.game.players[0].resources.wood=1);await page.locator('[data-modal-action="load"]').click();assert.ok(Math.abs(await state(()=>__CROWN.game.players[0].resources.wood)-saved)<10);assert.equal(await page.locator('#modalRoot').isVisible(),false);await page.evaluate(()=>__CROWN.game.paused=true);});
await test('How-to-play dialog describes controls and restores pause state',async()=>{await page.locator('#helpButton').click();assert.match(await page.locator('#modalRoot').textContent(),/Cross the stone bridges/);await page.locator('[data-modal-action="resume"]').click();assert.equal(await state(()=>__CROWN.game.paused),true);});
await test('Victory opens a score screen and a new match resets the simulation',async()=>{await page.evaluate(()=>{const g=__CROWN.game;const e=g.own(1,'building').find(e=>e.type==='towncenter');e.hp=10;const ram=g.addUnit('ram',0,e.x-2,e.y);g.command([ram.id],e);});await sim(2);await page.waitForTimeout(800);assert.match(await page.locator('#modalRoot').textContent(),/An empire, forged/);await page.locator('[data-modal-action="new"]').click();await page.locator('[data-difficulty="relaxed"]').click();await page.locator('[data-modal-action="start"]').click();assert.equal(await state(()=>__CROWN.game.difficulty),'relaxed');assert.equal(await state(()=>__CROWN.game.players[0].age),0);assert.equal(await state(()=>__CROWN.game.population()),10);});
await page.waitForTimeout(5000);await page.screenshot({path:'tests/desktop.png'});
await test('A compact desktop layout keeps game controls within the viewport',async()=>{await page.setViewportSize({width:1100,height:740});await page.waitForTimeout(500);assert.equal(await state(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'tests/compact.png'});});
await test('A phone layout renders without page overflow and retains commands',async()=>{await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);assert.equal(await state(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('[data-action="train:villager"]').isVisible(),true);await page.screenshot({path:'tests/mobile.png'});});
await test('The mobile objective checklist can be expanded and collapsed',async()=>{assert.equal(await page.locator('#journeySteps').isVisible(),false);await page.locator('#journeyToggle').click();assert.equal(await page.locator('#journeySteps').isVisible(),true);await page.locator('#journeyToggle').click();assert.equal(await page.locator('#journeySteps').isVisible(),false);});
await test('Late-game buildings, siege, and cavalry render without errors',async()=>{await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>{const {game:g,renderer:r}=__CROWN;g.paused=true;g.players[0].age=3;for(const [type,x,y]of [['castle',27,23],['workshop',31,16],['stable',28,28],['blacksmith',28,19],['market',24,28],['tower',25,20],['range',32,21]])g.addBuilding(type,0,x,y);const treb=g.addUnit('trebuchet',0,25,24);g.addUnit('ram',0,26,25);g.addUnit('knight',0,26,27);g.updateVision();r.focus({x:28,y:23});__CROWN.select([treb.id]);__CROWN.refresh(true);});await page.waitForTimeout(400);await page.screenshot({path:'tests/imperial.png'});assert.equal(await page.locator('#selectionName').textContent(),'Trebuchet');});
assert.deepEqual(errors,[]);console.log(`\n${result.length} browser tests passed. No browser errors.`);
}finally{await browser.close();}
