// GENERATED by tools/audio-check.mjs --calibrate-music : per mood+instrument gain multipliers of the generative score
// (MIX) and the per-mood output scale (LEVEL).
export const MIX = {
  "battle.brass": 0.7483,
  "battle.cymbal": 10.2979,
  "battle.drum": 1.2489,
  "battle.lute": 2.9389,
  "battle.shawm": 0.332,
  "battle.str": 1.1141,
  "battle.timp": 1.9567,
  "peace.drone": 0.1465,
  "peace.flute": 0.1809,
  "peace.ghost": 0.1647,
  "peace.lute": 1.0192,
  "peace.pad": 0.3001,
  "tense.drone": 0.2566,
  "tense.drum": 2.0297,
  "tense.flute": 0.3349,
  "tense.ghost": 0.8994,
  "tense.lute": 4.4181,
  "tense.str": 0.8752,
};
export const LEVEL = {"peace":0.164,"tense":0.0819,"battle":0.0884};
